version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - misspell

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
